server:
  port: 8084

spring:
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 10

  data:
    mongodb:
      uri: mongodb://localhost:27017/feedback

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8082/realms/selmag


logging:
  level:
    root: INFO
#    org.springframework.data.mongodb: DEBUG
#    org.mongodb.driver: WARN
    org.springframework.security: DEBUG
    org.springframework.boot.autoconfigure.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    org.springframework.security.oauth2.server.resource: DEBUG
    org.springframework.security.oauth2.jwt: DEBUG