server:
  port: 8084

spring:
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 10

  data:
    mongodb:
      uri: mongodb://localhost:27017/feedback


logging:
  level:
    root: INFO
    org.springframework.data.mongodb: DEBUG
    org.mongodb.driver: WARN